### PR TITLE
Delete files when writing contents to them instead of just truncating…

### PR DESCRIPTION
**Pull request by hategan**
… so that versioning checkpoints using hard links work properly

### CODE REVIEW

**Comment by Xarthisius** [comment]
I had to make the following changes for it to work:

```diff
diff --git a/server/__init__.py b/server/__init__.py
index 5472ddc..db86b0d 100644
--- a/server/__init__.py
+++ b/server/__init__.py
@@ -2,6 +2,8 @@
 # -*- coding: utf-8 -*-
 
 import cherrypy
+from bson.objectid import ObjectId
+from bson.errors import InvalidId
 import os
 import pathlib
 import tempfile
@@ -130,31 +132,28 @@ def setDefaults():
 def setHomeFolderMapping(root: str):
     def fn(event: events.Event):
         user = event.info
+        userId = user["_id"]
+        if userId and not isinstance(userId, ObjectId):
+            try:
+                userId = ObjectId(userId)
+            except InvalidId:
+                raise ValidationException('Invalid ObjectId: %s' % userId, field="id")
         m = HomePathMapper()
         absDir = '%s/%s' % (root, m.davToPhysical('/' + user['login']))
-        homeFolder = Folder().findOne({'parentId': user['_id'], 'name': 'Home'})
-        homeFolder.update({'fsPath': absDir, 'isMapping': True})
-        # We don't want to trigger events here, amirite?
-        Folder().save(homeFolder, False)
-
+        homeFolder = Folder().findOne({'parentId': userId, 'name': 'Home'})
+        if homeFolder:
+            homeFolder.update({'fsPath': absDir, 'isMapping': True})
+            # We don't want to trigger events here, amirite?
+            Folder().save(homeFolder, False)
     return fn
 
 
 def setTaleFolderMapping(root: str):
     def fn(event: events.Event):
         tale = event.info
-        # <WORKSPACE_NAME>[collection]/<WORKSPACE_NAME>[folder]/<tale_id>[folder]
-
-        rootCol = Collection().findOne({'name': WORKSPACE_NAME})
-        rootFolder = Folder().findOne({'name': WORKSPACE_NAME, 'parentId': rootCol['_id']})
-        workspace = Folder().findOne({'name': str(tale['_id']), 'parentId': rootFolder['_id']})
-
-        if workspace is None:
-            # there are two saves when a tale is created: one before all the aux folders (including
-            # the workspace folder) are created and one after. This handler will get called in both
-            # cases, and we need to wait for the latter call, which this test does.
+        if not "workspaceId" in tale:
             return
-
+        workspace = Folder().load(tale["workspaceId"], force=True)
         m = TalePathMapper()
         absDir = '%s/%s' % (root, m.davToPhysical('/' + str(tale['_id'])))
         pathlib.Path(absDir).mkdir(parents=True, exist_ok=True)
```

In both cases code was operating on a JSON serialized model of a user and tale respectively and using methods (`findOne`) that expect `ObjectId` instead of string for an Id.

**Comment by hategan** [comment]
I was working with the assumption that all users have a home folder set up when they are created and the same for tale workspaces. I mean, I think these assumptions are made in many places, so having conditional things here only pushes the issue to occur later. No?

**Comment by Xarthisius** [comment]
> I was working with the assumption that all users have a home folder set up when they are created and the same for tale workspaces. I mean, I think these assumptions are made in many places, so having conditional things here only pushes the issue to occur later. No?

Conditional is probably unnecessary. I made it before I realized that it's the `str` vs `ObjectId`

**Comment by hategan** [comment]
Odd. When would user not be a proper girder dict?

**Review by Xarthisius — APPROVED** [review]

**Pull request merged**
